display_errors = Off
display_startup_errors = Off
log_errors = On
error_log = /var/www/html/storage/logs/php_errors.log
error_reporting = E_ALL

[opcache]
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=128
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=10000
opcache.validate_timestamps=0

expose_php = Off               ; Ne pas exposer la version PHP dans les headers
session.cookie_httponly = 1   ; Sécurité cookies
session.cookie_secure = 1     ; Force HTTPS pour les cookies (si tu es en HTTPS)
session.use_strict_mode = 1   ; Empêche l’utilisation de sessions non initialisées
memory_limit = 256M           ; Augmente si ton CMS monte en puissance
max_execution_time = 30       ; Adapte selon tes besoins (API longues par ex)
