---
deployment:
  tasks:
    - export DEPLOYPATH=/home/renoveco/
    - /bin/cp -rf core $DEPLOYPATH
    - /bin/cp -rf config $DEPLOYPATH
    - /bin/cp -rf src $DEPLOYPATH
    - /bin/cp -rf public $DEPLOYPATH/public_html
