# Ce fichier docker-compose.yaml orchestre tous les services nécessaires à une application Symfony complète : 
# -> un conteneur PHP pour le back-end, MySQL pour les données, Nginx pour servir les requêtes, et PhpMyAdmin pour l'administration des bases. 
# Grâce à Docker, tout est isolé et portable, simplifiant le développement et la gestion du projet.

services:
  # Service PHP : Définit un conteneur pour exécuter le code PHP.
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: frankenphp
    ports:
      - "443:443" # HTTPS via FrankenPHP (Caddy intégré)
    volumes:
      # Dossiers et fichiers montés pour le code source et les dépendances PHP.
      - ./:/app

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    working_dir: /app
    volumes:
      - ./package-lock.json:/app/package-lock.json
      - ./package.json:/app/package.json
      - ./public:/app/public
      - ./src/assets:/app/src/assets
      - ./webpack.config.js:/app/webpack.config.js

  mysql:
    image: mysql:latest # Utilise l'image officielle MySQL version (ex: 8.0.39).
    environment:
      # Définit les variables d'environnement pour configurer la base de données.
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Mot de passe pour l'utilisateur root (administrateur de la base).
    volumes:
      - db_data:/var/lib/mysql # Stocke les données de la base dans un volume nommé 'db_data' pour la persistance.
      - ./docker/mysql/init:/docker-entrypoint-initdb.d # Monte le dossier d'initialisation pour exécuter des scripts SQL au démarrage.
    ports:
      - "3306:3306" # Expose le port 3306 du conteneur sur le port 3306 de la machine hôte pour permettre l'accès à MySQL.

  # Service PhpMyAdmin : Interface web pour gérer visuellement la base de données MySQL.
  phpmyadmin:
    image: phpmyadmin/phpmyadmin # Utilise l'image officielle PhpMyAdmin.
    environment:
      # Définit les variables d'environnement pour PhpMyAdmin.
      PMA_HOST: mysql # Indique que le service MySQL est l'hôte de la base de données.
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Mot de passe root pour accéder à toutes les bases de données.
    ports:
      - "8081:80" # Expose le port 80 du conteneur sur le port 8081 de la machine hôte.

# Déclare un volume Docker pour stocker les données MySQL et les rendre persistantes.
volumes:
  db_data: # Déclare un volume pour MySQL
  node_modules_data:
