# Ce fichier docker-compose.yaml orchestre tous les services nécessaires à une application Symfony complète : 
# -> un conteneur PHP pour le back-end, MySQL pour les données, Nginx pour servir les requêtes, et PhpMyAdmin pour l'administration des bases. 
# Grâce à Docker, tout est isolé et portable, simplifiant le développement et la gestion du projet.

services:
  # Service PHP : Définit un conteneur pour exécuter le code PHP.
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html # uniquement le backend PHP
      - vendor_data:/var/www/html/vendor # isole le dossier vendor pour éviter les conflits de permissions
      - ./secure:/var/www/secure # // Stockage des fichiers sécurisés. (ex: env.prod.key)
      - ./tmp:/var/www/tmp # Monte le dossier de configuration PHP personnalisé.
      - ./.env.local.enc:/var/www/.env.local.enc # Fichier chiffré local
      - ./.env.dev.enc:/var/www/.env.dev.enc # Fichier chiffré dev
      - ./.env.prod.enc:/var/www/.env.prod.enc # Fichier chiffré versionné
      - certs:/etc/ssl/mkcert # Monte le volume contenant les certificats
    ports:
      - "9000:9000" # Expose le port 9000 du conteneur sur le port 9000 de la machine hôte pour les requêtes PHP.
    depends_on:
      - mysql

  # Service Nginx : Configure un serveur web pour traiter les requêtes HTTP et les transmettre à PHP.
  nginx:
    image: nginx:alpine # Utilise l'image officielle Nginx en version légère (alpine).
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
      - ./storage/logs:/var/log/nginx
      - certs:/etc/ssl/mkcert # Ce volume est partagé avec le conteneur PHP
    ports:
      - "443:443" # Expose le port 443 du conteneur sur le port 443 de la machine hôte.
    depends_on:
      - php # Assure que le conteneur PHP est prêt avant de démarrer ce service.

  # Service MySQL : Fournit une base de données MySQL pour stocker les données de l'application.
  mysql:
    image: mysql:latest # Utilise l'image officielle MySQL version (ex: 8.0.39).
    environment:
      # Définit les variables d'environnement pour configurer la base de données.
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Mot de passe pour l'utilisateur root (administrateur de la base).
    volumes:
      - db_data:/var/lib/mysql # Stocke les données de la base dans un volume nommé 'db_data' pour la persistance.
      - ./docker/mysql/init:/docker-entrypoint-initdb.d # Monte le dossier d'initialisation pour exécuter des scripts SQL au démarrage.
    ports:
      - "3306:3306" # Expose le port 3306 du conteneur sur le port 3306 de la machine hôte pour permettre l'accès à MySQL.

  # Service PhpMyAdmin : Interface web pour gérer visuellement la base de données MySQL.
  phpmyadmin:
    image: phpmyadmin/phpmyadmin # Utilise l'image officielle PhpMyAdmin.
    environment:
      # Définit les variables d'environnement pour PhpMyAdmin.
      PMA_HOST: mysql # Indique que le service MySQL est l'hôte de la base de données.
      MYSQL_ROOT_PASSWORD: rootpassword # Mot de passe root pour accéder à toutes les bases de données.
    ports:
      - "8081:80" # Expose le port 80 du conteneur sur le port 8081 de la machine hôte.

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    working_dir: /app
    volumes:
      - ./app/assets:/app/app/assets
      - ./public:/app/public
      - ./webpack.config.js:/app/webpack.config.js
      # Déclare un volume Docker pour stocker les données MySQL et les rendre persistantes.
volumes:
  db_data: # Déclare un volume pour MySQL
  certs: # Déclare un volume pour les certificats
  vendor_data:
  node_modules_data:
