services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: frankenphp
    ports:
      - "443:443" # HTTPS via FrankenPHP (Caddy intégré)
    volumes:
      - ./:/app

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    working_dir: /app
    ports:
      - "5173:5173" # (port de Vite)
    volumes:
      - ./package-lock.json:/app/package-lock.json
      - ./package.json:/app/package.json
      - ./public:/app/public
      - ./src/assets:/app/src/assets
      - ./vite.config.js:/app/vite.config.js

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} # Mot de passe pour l'utilisateur root.
    volumes:
      - db_data:/var/lib/mysql # Stocker les données de la base pour la persistance des données (db_data)
      - ./docker/mysql/init:/docker-entrypoint-initdb.d # Monter le dossier d'initialisation pour exécuter le script SQL au démarrage.
    ports:
      - "3306:3306" # Expose le port 3306 du conteneur sur le port 3306 de la machine hôte pour permettre l'accès à MySQL.

  # Service PhpMyAdmin : Interface web pour gérer visuellement la base de données MySQL.
  phpmyadmin:
    depends_on:
      - mysql # garantit que mysql démarre avant
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql # Indique que le service MySQL est l'hôte de la base de données.
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} # Mot de passe pour accéder à la base de donnée (à sa création)
    ports:
      - "8081:80"

# Volumes pour les données persistantes
volumes:
  db_data:
