<?php
return [
    'user' => [
        'About\AboutIndexController@index',
        'Admin\AdminDashboardController@index',
        'Auth\AuthIndexController@login',
        'Auth\AuthIndexController@registerJson',
        'Auth\AuthLoginController@connection',
        'Auth\AuthLoginController@login',
        'Cgu\CguIndexController@index',
        'Contact\ContactIndexController@index',
        'Contact\ContactIndexController@mailSend',
        'Home\HomeIndexController@index',
        'Product\ProductDetailController@detail',
        'Product\ProductListController@list',
        'User\UserIndexController@create',
        'User\UserCreateController@registerJson',
        'User\UserCreateController@create',
        'User\UserCreateController@store',
        'Utilities\SitemapController@index',
        'Gallery\GalleryIndexController@index',
        'Cgu\CguPolicyController@policy',
        'Services\DetailController@detail',
        'Auth\AuthLoginController@logout',
    ],
    'admin' => [
        '*', // accès total
    ],
    'superadmin' => [
        '*', // accès total
    ],
    'guest' => [
        'About\AboutIndexController@index',
        'Admin\AdminDashboardController@index',
        'Auth\AuthIndexController@login',
        'Auth\AuthIndexController@registerJson',
        'Auth\AuthLoginController@connection',
        'Auth\AuthLoginController@login',
        'Cgu\CguIndexController@index',
        'Contact\ContactIndexController@index',
        'Contact\ContactIndexController@mailSend',
        'Home\HomeIndexController@index',
        'Product\ProductDetailController@detail',
        'Product\ProductListController@list',
        'User\UserIndexController@create',
        'User\UserCreateController@registerJson',
        'User\UserCreateController@create',
        'User\UserCreateController@store',
        'Utilities\SitemapController@index',
        'Gallery\GalleryIndexController@index',
        'Cgu\CguPolicyController@policy',
        'Services\DetailController@detail',
        // -- new-line-generate-by-make-module --
    ],
];
